test/data/err_131.py:6:1 [FURB131]: Replace `del nums[:]` with `nums.clear()`
